// 정산 사이트 모의 서버 — biz_new-main 소스(컨트롤러·서비스·매퍼·화면JS)에서 확인한 동작만 구현
import http from 'node:http';
const sessions = new Map(); const users = { admin: { pw: 'adminpw', role: 'ADMIN', rate: 1 }, yongyong: { pw: 'yy1234', role: 'USER', rate: 1 }, typ2uh: { pw: 'tt', role: 'USER', rate: 0.3 } };
const customers = [{ bizNo: '1111111111', custName: '업체1', empId: 'yongyong', mileage: 50000, incentiveRate: 0 }, { bizNo: '2222222222', custName: '채움창', empId: 'yongyong', mileage: 0, incentiveRate: 0.5 }];
const products = [{ prodId: 'PD-0060', prodName: '선입금킵', prodAmt: 0, prodIncentive: 0 }, { prodId: 'PD-0001', prodName: '셀팜', prodAmt: 27.5, prodIncentive: 0 }, { prodId: 'PD-0099', prodName: '상품인센테스트', prodAmt: 10, prodIncentive: 3 }];
const codes = { SE02: [{ baseCode: '01', codeName: '신규' }, { baseCode: '02', codeName: '연장' }, { baseCode: '05', codeName: '선입금' }], SE04: { '01': '승인요청', '02': '승인완료', '03': '승인취소', C: '요청취소' } };
const settlement = []; const settlementmst = []; const mileageHis = []; let seqNo = 0, confNo = 0; const today = () => new Date(Date.now() + 9 * 3600e3).toISOString().slice(0, 10);
const log = [];
const send = (res, code, body, headers = {}) => { res.writeHead(code, { 'Content-Type': 'application/json', ...headers }); res.end(typeof body === 'string' ? body : JSON.stringify(body)); };
const err500 = (res, path) => send(res, 500, { timestamp: new Date().toISOString(), status: 500, error: 'Internal Server Error', path });
const readBody = req => new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b)); });
const sessOf = req => { const m = /JSESSIONID=([A-Z0-9]+)/.exec(req.headers.cookie || ''); return m ? sessions.get(m[1]) : null; };
http.createServer(async (req, res) => {
  const u = new URL(req.url, 'http://x'); const q = Object.fromEntries(u.searchParams); const path = u.pathname; const body = await readBody(req);
  log.push(`${req.method} ${path}${body ? ' ' + body.slice(0, 300) : ''}`);
  if (path === '/login' && req.method === 'GET') { const sid = 'PRE' + Math.random().toString(36).slice(2).toUpperCase(); sessions.set(sid, null); res.writeHead(200, { 'Content-Type': 'text/html', 'Set-Cookie': `JSESSIONID=${sid}; Path=/; HttpOnly` }); return res.end('<html><form method="post" action="/login_proc"><select name="coCode"><option value="C001">참한</option></select><input name="userId"><input name="userPw"></form></html>'); }
  if (path === '/login_proc' && req.method === 'POST') { const p = Object.fromEntries(new URLSearchParams(body)); const u2 = users[p.userId]; if (!u2 || u2.pw !== p.userPw || p.coCode !== 'C001') { res.writeHead(302, { Location: 'http://x/login?error=true' }); return res.end(); } const sid = 'S' + Math.random().toString(36).slice(2).toUpperCase(); sessions.set(sid, { userId: p.userId, role: u2.role, coCode: p.coCode }); res.writeHead(302, { Location: 'http://x/', 'Set-Cookie': `JSESSIONID=${sid}; Path=/; HttpOnly` }); return res.end(); }
  if (path === '/__state') return send(res, 200, { settlement, settlementmst, customers, mileageHis, log });
  const s = sessOf(req); if (!s) { res.writeHead(302, { Location: 'http://x/login' }); return res.end(); }
  if (req.headers['x-requested-with'] !== 'XMLHttpRequest' && path.startsWith('/api/')) return err500(res, path);   // 브라우저 직접 접근 시 500 재현
  const row = st => { const sm = settlementmst.find(m => m.settlementSeq === st.settlementSeq); const c = customers.find(c => c.bizNo === st.custId); const p = products.find(p => p.prodId === st.prodId); return { ...st, custName: c?.custName, prodName: p?.prodName, empName: st.userId, confirmSeq: sm?.confirmSeq ?? '', confirmAmt: sm?.confirmAmt ?? '0', confirmMileage: sm?.confirmMileage ?? '', confirmRateAmt: sm?.confirmRateAmt ?? '', confirmInd: sm ? 'Y' : '', statusName: codes.SE04[st.applyStatus], gubunName: codes.SE02.find(g => g.baseCode === st.gubun)?.codeName ?? '', reqGubunName: st.reqGubun === 'AQ' ? '정산요청' : st.reqGubun, dispReqDate: st.reqDate, incomAmt: String(Number(st.saleTotalAmt) - Number(st.prodTotalAmt)), applyStatusName: codes.SE04[st.applyStatus] }; };
  // ---- 정산승인관리 ----
  if (path === '/api/pages/applypaymentapprmng' && req.method === 'GET') { let list = settlement.filter(st => st.applyStatus !== 'C' && st.reqDate >= q.searchStartDate && st.reqDate <= q.searchEndDate); if (q.applyStatus) list = list.filter(st => st.applyStatus === q.applyStatus); return send(res, 200, list.map(row)); }
  if (path === '/api/pages/applypaymentapprmng' && req.method === 'POST') { const p = JSON.parse(body); const st = settlement.find(x => x.settlementSeq === p.settlementSeq); if (!st) return send(res, 500, '처리 도중 오류가 발생했습니다11.'); st.applyStatus = '02'; const cs = `${today().replace(/-/g, '')}-${String(++confNo).padStart(4, '0')}`; let confirmAmt = p.confirmAmt, confirmRateAmt = p.confirmRateAmt, confirmMileage = p.confirmMileage; if (st.refundInd === 'Y') { confirmAmt = st.refundProdTotalAmt; confirmRateAmt = st.refundExpectRateAmt; if (st.gubun === '04') confirmMileage = st.refundProdTotalAmt; } settlementmst.push({ confirmSeq: cs, settlementSeq: st.settlementSeq, userId: st.userId, confirmAmt: String(confirmAmt === '' ? 0 : Number(confirmAmt)), confirmMileage: String(confirmMileage === '' ? 0 : Number(confirmMileage)), confirmRateAmt: String(confirmRateAmt === '' ? 0 : Number(confirmRateAmt)), remark: p.remark ?? null }); const m = Number(confirmMileage) || 0; if (m > 0) { const c = customers.find(c => c.bizNo === st.custId); c.mileage += m; mileageHis.push({ bizNo: st.custId, amt: m, page: 'SC' }); } return send(res, 200, '1'); }
  if (path === '/api/pages/applypaymentapprmng/cancel' && req.method === 'POST') { const p = JSON.parse(body); const st = settlement.find(x => x.settlementSeq === p.settlementSeq); const smi = settlementmst.findIndex(m => m.settlementSeq === p.settlementSeq); if (smi >= 0 && settlementmst[smi].payYm) return send(res, 500, '이미 급여처리가 진행된 요청 건입니다.'); if (smi >= 0) settlementmst.splice(smi, 1); if (!st) return send(res, 200, '0'); st.applyStatus = '03'; return send(res, 200, '1'); }
  // ---- 정산요청 ----
  if (path === '/api/pages/applypayment/find/incentiveRate') return send(res, 200, String(users[q.userId]?.rate ?? 0));
  if (path === '/api/pages/applypayment/custinfo') { const c = customers.find(c => c.bizNo === q.bizNo); return send(res, 200, c ? { bizNo: c.bizNo, custName: c.custName, mileage: String(c.mileage), incentiveRate: String(c.incentiveRate) } : null); }
  if (path === '/api/pages/applypayment/prodinfo') { const p = products.find(p => p.prodId === q.prodId); return send(res, 200, p ? { prodId: p.prodId, prodName: p.prodName, prodAmt: String(p.prodAmt), prodIncentive: String(p.prodIncentive), useInd: 'Y' } : null); }
  if (path === '/api/pages/applypayment' && req.method === 'GET') { let list = settlement.filter(st => !st.refundInd && st.reqGubun === 'AQ' && st.reqDate >= q.searchStartDate && st.reqDate <= q.searchEndDate); if (s.role !== 'ADMIN') list = list.filter(st => st.userId === s.userId); return send(res, 200, list.map(st => ({ ...row(st), userName: st.userId, curExistMileage: st.existMileage }))); }
  if (path === '/api/pages/applypayment' && req.method === 'POST') { const p = JSON.parse(body); if (p.rowStatus !== 'C') return send(res, 200, '0'); const seq = `S${today().replace(/-/g, '')}-${String(++seqNo).padStart(4, '0')}`; const st = { ...p, settlementSeq: seq, reqDate: today(), reqGubun: 'AQ', applyStatus: '01', refundInd: null }; settlement.push(st); if (p.mileageUseInd === 'Y') { const c = customers.find(c => c.bizNo === p.custId); const use = Number(p.useMileage); if (c.mileage - use < 0) { settlement.pop(); return send(res, 500, `킵 사용금액이 잔여킵금액보다 같거나 더 적어야 합니다.\n잔여킵금액: ${c.mileage}\n킵사용금액: ${-use}`); } c.mileage -= use; mileageHis.push({ bizNo: c.bizNo, amt: -use, page: 'AQ', by: s.userId }); } return send(res, 200, '1'); }
  if (path === '/api/pages/applypayment/cancel' && req.method === 'POST') { const p = JSON.parse(body); let n = 0; for (const d of p.settlementDtoList) { const st = settlement.find(x => x.settlementSeq === d.settlementSeq); if (!st || st.applyStatus !== '01') return send(res, 500, '승인요청건만 삭제 가능합니다.'); st.applyStatus = 'C'; n++; if (d.mileageUseInd === 'Y') { const c = customers.find(c => c.bizNo === d.custId); c.mileage += Number(d.useMileage); } } return send(res, 200, String(n)); }
  // ---- 고객·상품·코드 ----
  if (path === '/api/pages/customer' && req.method === 'GET') return send(res, 200, customers.map(c => ({ ...c, mileage: String(c.mileage), incentiveRate: String(c.incentiveRate), useInd: 'Y', regDate: '2026-01-01' })));
  if (path === '/api/pages/customer' && req.method === 'POST') { const p = JSON.parse(body); if (p.isNew && customers.some(c => c.bizNo === p.bizNo)) return send(res, 500, '동일한 사업번호와 직원의 데이터가 존재합니다.'); if (!p.bizNo) return send(res, 500, 'bizNo required'); customers.push({ bizNo: p.bizNo, custName: p.custName, empId: p.empId, mileage: 0, incentiveRate: Number(p.incentiveRate) || 0 }); return send(res, 200, '2'); }
  if (path === '/api/pages/product/pop/list') return send(res, 200, products);
  if (path === '/api/system/codes/pages' && req.method === 'POST') return send(res, 200, { SE02: codes.SE02 });
  if (path === '/__state') return send(res, 200, { settlement, settlementmst, customers, mileageHis, log });
  return send(res, 404, { status: 404, error: 'Not Found', path });
}).listen(18080, () => console.log('mock on 18080'));
