'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { notify } from '@/components/Toast';
import { testConnection, saveFieldMap, syncNow, saveEmplMap, hideEmpl } from '@/app/admin/settlement/actions';
import { addDays, fmtKST } from '@/lib/date/kst';
type Run = { id: number; started_at: string; finished_at: string | null; ok: boolean | null; message: string | null; rows_fetched: number; rows_applied: number; range_from: string | null; range_to: string | null; triggered_by: string | null };
const FIELDS: [string, string][] = [['settle_no', '정산번호 (중복 방지 키)'], ['empl_id', '담당자 ID'], ['req_date', '요청일'], ['profit', '영업이익'], ['status', '진행상태']];
export default function SettlementAdmin({ isAdmin, summary, hiddenIds, map, vat, runs, emplIds, maps, people, total, today, envReady }: { isAdmin: boolean; summary: { months: string[]; rows: { empl: string; name: string; vals: number[] }[]; totals: number[] }; hiddenIds: { empl_id: string; name: string }[]; map: Record<string, string>; vat: string; runs: Run[]; emplIds: string[]; maps: { empl_id: string; user_id: string | null }[]; people: { id: string; name: string; email: string }[]; total: number; today: string; envReady: boolean }) {
  const r = useRouter(); const [test, setTest] = useState<any>(null); const [busy, setBusy] = useState(false); const [from, setFrom] = useState(addDays(today, -7)); const [to, setTo] = useState(today); const [prog, setProg] = useState('');
  async function runChunked() { setBusy(true); let s = from, i = 0; const chunks: string[][] = []; while (s <= to) { const e = addDays(s, 6) > to ? to : addDays(s, 6); chunks.push([s, e]); s = addDays(e, 1); } let okAll = true;
    for (const [a, b] of chunks) { i++; setProg(`${i}/${chunks.length} · ${a.slice(5)}~${b.slice(5)}`); const x = await syncNow(a, b); if (!x.ok) { okAll = false; notify(x.msg); break; } }
    setBusy(false); setProg(''); if (okAll) notify(`${from}~${to} 동기화 완료 (${chunks.length}회)`); r.refresh(); }
  const keys: string[] = test?.keys ?? Object.values(map).filter(Boolean);
  const auto = (empl: string) => people.find(p => p.email.split('@')[0] === empl);
  const mapped = !!(map.settle_no && map.empl_id && map.req_date && map.profit && map.status);
  return (
    <div style={{ display: 'grid', gap: 18 }}>
      <h1 style={{ fontSize: 20, margin: 0 }}>정산 연동 <span style={{ fontSize: 13, color: 'var(--muted)', fontWeight: 400 }}>lchkgy.com 정산승인 → 담당자·요청일별 영업이익 ÷{vat} → KPI 자동 마진 · 누적 {total.toLocaleString()}건</span></h1>
      {isAdmin && !envReady && <div style={{ background: 'var(--bad-soft)', color: 'var(--bad)', padding: '10px 14px', borderRadius: 10, fontSize: 13 }}>Vercel 환경변수 <b>SETTLE_CO_CODE · SETTLE_USER_ID · SETTLE_USER_PW</b>(정산 사이트 어드민 계정)가 없습니다. 추가 후 Redeploy.</div>}
      <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15 }}>정산 담당자별 월 마진 <span style={{ fontSize: 12, color: 'var(--muted)', fontWeight: 400 }}>정산 ID 기준 · 승인완료 · ÷{vat} 올림 · 21일~20일 월 · 매핑 여부와 무관</span></h3>
        <div style={{ overflowX: 'auto' }}><table><thead><tr><th>정산 ID</th><th>이름</th><th>워크허브 계정</th>{summary.months.map(m => <th key={m} style={{ textAlign: 'right' }}>{Number(m.slice(5))}월</th>)}</tr></thead><tbody>
          {summary.rows.map(r => { const m = maps.find(x => x.empl_id === r.empl); const a = auto(r.empl); const acct = m ? people.find(p => p.id === m.user_id) : a; return <tr key={r.empl}><td><b>{r.empl}</b></td><td>{r.name}</td><td style={{ color: acct ? 'inherit' : 'var(--bad)', fontSize: 12.5 }}>{acct ? acct.name : '미매핑'}</td>{r.vals.map((val, i) => <td key={i} style={{ textAlign: 'right', fontVariantNumeric: 'tabular-nums', color: val < 0 ? 'var(--bad)' : 'inherit' }}>{val ? '₩' + val.toLocaleString('ko-KR') : <span style={{ color: 'var(--line)' }}>·</span>}</td>)}</tr>; })}
          {summary.rows.length > 0 && <tr style={{ fontWeight: 700, background: 'var(--bg)' }}><td colSpan={3}>합계 <span style={{ fontSize: 11, color: 'var(--muted)', fontWeight: 400 }}>전체 합 ÷{vat} 올림 · 정산 사이트 기준</span></td>{summary.months.map((_, i) => <td key={i} style={{ textAlign: 'right' }}>₩{summary.totals[i].toLocaleString('ko-KR')}</td>)}</tr>}
          {summary.rows.length === 0 && <tr><td colSpan={4} style={{ color: 'var(--muted)' }}>동기화된 정산 없음</td></tr>}</tbody></table></div></div>
      <div style={{ display: 'grid', gridTemplateColumns: isAdmin ? '1fr 1fr' : '1fr', gap: 18 }}>
        {isAdmin && <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15 }}>1. 연결 테스트 → 2. 필드 매핑</h3>
          <button className="btn ghost" disabled={busy} onClick={async () => { setBusy(true); try { const x = await Promise.race([testConnection(), new Promise<any>((_, rej) => setTimeout(() => rej(new Error('60초 내 응답 없음 — 정산 사이트 응답 지연 또는 서버 함수 시간 초과')), 62000))]); setTest(x); notify(x.msg); } catch (e: any) { notify(e.message); } setBusy(false); }}>{busy ? '확인 중… (최대 60초)' : '연결 테스트 (로그인 + 최근 7일 조회)'}</button>
          {test?.sample && <div style={{ marginTop: 10, fontSize: 12, background: 'var(--bg)', padding: 10, borderRadius: 8, maxHeight: 160, overflow: 'auto', fontFamily: 'monospace' }}>{JSON.stringify(test.sample, null, 1)}</div>}
          <form action={async fd => { const x = await saveFieldMap(fd); notify(x.msg); if (x.ok) r.refresh(); }} style={{ display: 'grid', gap: 8, marginTop: 12 }}>
            {FIELDS.map(([k, l]) => <div key={k} style={{ display: 'grid', gridTemplateColumns: '150px 1fr', gap: 8, alignItems: 'center' }}><span style={{ fontSize: 12.5 }}>{l}</span>{keys.length ? <select name={k} defaultValue={map[k] || test?.guess?.[k] || ''}><option value="">선택</option>{keys.map(x => <option key={x} value={x}>{x}{test?.sample ? ` = ${String(test.sample[x]).slice(0, 24)}` : ''}</option>)}</select> : <input name={k} defaultValue={map[k] ?? ''} placeholder="연결 테스트 후 선택" />}</div>)}
            <div style={{ display: 'grid', gridTemplateColumns: '150px 1fr', gap: 8, alignItems: 'center' }}><span style={{ fontSize: 12.5 }}>승인 상태 값</span><input name="status_ok" defaultValue={map.status_ok ?? '승인완료'} /></div>
            <div style={{ display: 'grid', gridTemplateColumns: '150px 1fr', gap: 8, alignItems: 'center' }}><span style={{ fontSize: 12.5 }}>VAT 나누기</span><input name="vat" type="number" step="0.01" defaultValue={vat} /></div>
            <div><button className="btn">매핑 저장</button> <span style={{ fontSize: 12, color: mapped ? 'var(--ok)' : 'var(--bad)' }}>{mapped ? '매핑 완료' : '매핑 필요'}</span></div>
          </form></div>}
        <div style={{ display: 'grid', gap: 18, alignContent: 'start' }}>
          <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15 }}>3. 동기화 <span style={{ fontSize: 12, color: 'var(--muted)', fontWeight: 400 }}>GitHub Actions 매일 06:00 회사 연도(12/21~) 전체 재조회 · 아래는 소량 수동용</span></h3>
            <div style={{ fontSize: 12.5, background: 'var(--accent-soft)', color: 'var(--accent)', padding: '8px 12px', borderRadius: 8, marginBottom: 10 }}>긴 기간(한 달 이상)은 GitHub 저장소 › Actions › settle-sync › Run workflow 에서 시작일·종료일 넣고 실행하세요. 정산 사이트가 느려도 시간 제한 없이 끝까지 돕니다.</div>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><input type="date" value={from} onChange={e => setFrom(e.target.value)} style={{ width: 150 }} /><span>~</span><input type="date" value={to} onChange={e => setTo(e.target.value)} style={{ width: 150 }} /><button className="btn" disabled={busy || !mapped} onClick={runChunked}>{busy ? `실행 중… ${prog}` : '지금 동기화'}</button></div>
            <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 6 }}>7일씩 나눠 순서대로 실행됩니다. 창을 닫지 마세요.</div>
            <table style={{ marginTop: 12, fontSize: 12.5 }}><thead><tr><th>시각</th><th>기간</th><th>결과</th><th>실행</th></tr></thead><tbody>{runs.map(x => <tr key={x.id}><td style={{ whiteSpace: 'nowrap' }}>{fmtKST(x.started_at)}</td><td style={{ whiteSpace: 'nowrap' }}>{x.range_from?.slice(5)}~{x.range_to?.slice(5)}</td><td style={{ color: x.ok === false ? 'var(--bad)' : x.ok ? 'var(--ok)' : 'var(--muted)' }}>{x.message ?? (Date.now() - new Date(x.started_at).getTime() > 120000 ? '응답 없음 (시간 초과 추정) — 다시 실행' : '진행 중…')}</td><td>{x.triggered_by}</td></tr>)}{runs.length === 0 && <tr><td colSpan={4} style={{ color: 'var(--muted)' }}>실행 이력 없음</td></tr>}</tbody></table></div>
          <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15 }}>4. 담당자 매핑 <span style={{ fontSize: 12, color: 'var(--muted)', fontWeight: 400 }}>정산에 한 번이라도 나온 ID 전부 · 기본: ID = 워크허브 이메일 앞부분 · 다르면 지정 · 저장 후 재동기화 시 반영</span></h3>
            <form action={async fd => { const x = await saveEmplMap(fd); notify(x.msg); if (x.ok) r.refresh(); }}><table style={{ fontSize: 13 }}><thead><tr><th>정산 담당자ID</th><th>정산 이름</th><th>워크허브 계정</th></tr></thead><tbody>
              {emplIds.map(e => { const m = maps.find(x => x.empl_id === e); const a = auto(e); const nm = summary.rows.find(r => r.empl === e)?.name ?? ''; return <tr key={e}><td><b>{e}</b><input type="hidden" name="empl_id" value={e} /></td><td>{nm}</td><td><select name="user_id" defaultValue={m?.user_id ?? a?.id ?? ''}><option value="">— 미매핑 (KPI 반영 안 됨) —</option>{people.map(p => <option key={p.id} value={p.id}>{p.name} ({p.email.split('@')[0]}){a?.id === p.id && !m ? ' · 자동' : ''}</option>)}</select></td><td><button type="button" className="btn ghost" style={{ padding: '3px 8px', fontSize: 11 }} onClick={async () => { if (!confirm(`${e} (${nm}) 숨길까요? 표·매핑·KPI에서 제외되고 동기화해도 다시 안 나옵니다.`)) return; const x = await hideEmpl(e, true); notify(x.msg); r.refresh(); }}>숨김</button></td></tr>; })}
              {emplIds.length === 0 && <tr><td colSpan={3} style={{ color: 'var(--muted)' }}>동기화 후 담당자 ID가 여기 나타납니다</td></tr>}</tbody></table>{emplIds.length > 0 && <button className="btn" style={{ marginTop: 10 }}>매핑 저장</button>}</form>
            {hiddenIds.length > 0 && <details style={{ marginTop: 12 }}><summary style={{ cursor: 'pointer', fontSize: 12.5, color: 'var(--muted)' }}>숨긴 ID {hiddenIds.length}개 (퇴사자 등)</summary><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 8 }}>{hiddenIds.map(h => <span key={h.empl_id} className="pill" style={{ background: 'var(--bg)', color: 'var(--muted)' }}>{h.empl_id} {h.name} <button type="button" style={{ border: 0, background: 'none', color: 'var(--accent)', cursor: 'pointer', fontSize: 11 }} onClick={async () => { const x = await hideEmpl(h.empl_id, false); notify(x.msg); r.refresh(); }}>복원</button></span>)}</div></details>}</div>
        </div>
      </div>
    </div>
  );
}
