'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { won, man } from '@/lib/date/kst';
const n = (v: unknown) => Number(String(v ?? '0').replace(/[^\d.-]/g, '')) || 0;
export default function DataClient({ tab, bm, label, prev, next, rows, err, q }: { tab: string; bm: string; label: string; prev: string; next: string; rows: any[]; err: string; q: string }) {
  const r = useRouter(); const [s, setS] = useState(q);
  const go = (t: string, m = bm, qq = s) => r.push(`/settle-data?t=${t}&m=${m}${qq ? `&q=${encodeURIComponent(qq)}` : ''}`);
  const Tab = ({ k, l }: { k: string; l: string }) => <button className="btn ghost" style={{ padding: '6px 12px', fontSize: 13, background: tab === k ? 'var(--accent-soft)' : undefined, color: tab === k ? 'var(--accent)' : undefined, borderColor: tab === k ? 'var(--accent)' : undefined }} onClick={() => go(k)}>{l}</button>;
  const f = (x: any) => !s || JSON.stringify(x).toLowerCase().includes(s.toLowerCase());
  const R = rows.filter(f);
  const monthNav = tab !== 'customers' && <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><button className="btn ghost" style={{ padding: '4px 10px' }} onClick={() => go(tab, prev)}>‹</button><b>{label}</b><button className="btn ghost" style={{ padding: '4px 10px' }} onClick={() => go(tab, next)}>›</button></div>;
  return (
    <div style={{ display: 'grid', gap: 18 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}><h1 style={{ fontSize: 20, margin: 0 }}>정산 데이터</h1><Tab k="bycust" l="고객별 마진" /><Tab k="customers" l="고객 마스터" /><Tab k="tax" l="세금계산서" /><Tab k="payroll" l="수수료 지급" />{monthNav}<input value={s} onChange={e => setS(e.target.value)} onKeyDown={e => e.key === 'Enter' && go(tab)} placeholder="검색 (엔터)" style={{ width: 200, padding: '6px 10px' }} /><span style={{ fontSize: 12, color: 'var(--muted)' }}>정산 사이트 조회 전용 · 10분 캐시</span></div>
      {err && <div style={{ background: 'var(--bad-soft)', color: 'var(--bad)', padding: '10px 14px', borderRadius: 10, fontSize: 13 }}>{err}</div>}
      <div className="card"><div style={{ overflowX: 'auto' }}>
        {tab === 'bycust' && <table style={{ fontSize: 13 }}><thead><tr><th>#</th><th>고객</th><th>담당자</th><th style={{ textAlign: 'right' }}>건수</th><th style={{ textAlign: 'right' }}>영업이익 (VAT제외 올림)</th></tr></thead><tbody>{R.map((x, i) => <tr key={i}><td style={{ color: 'var(--muted)' }}>{i + 1}</td><td><b>{x.cust_name}</b></td><td>{x.empl_name} <span style={{ fontSize: 11, color: 'var(--muted)' }}>{x.empl_id}</span></td><td style={{ textAlign: 'right' }}>{x.cnt}</td><td style={{ textAlign: 'right', fontWeight: 600, color: n(x.sum_profit) < 0 ? 'var(--bad)' : 'inherit' }}>{won(Math.ceil(n(x.sum_profit) / 1.1))}</td></tr>)}{R.length === 0 && <tr><td colSpan={5} style={{ color: 'var(--muted)', textAlign: 'center', padding: 20 }}>데이터 없음</td></tr>}</tbody>
          {R.length > 0 && <tfoot><tr style={{ fontWeight: 700, background: 'var(--bg)' }}><td colSpan={3}>합계 ({R.length} 고객)</td><td style={{ textAlign: 'right' }}>{R.reduce((a, x) => a + n(x.cnt), 0)}</td><td style={{ textAlign: 'right' }}>{won(Math.ceil(R.reduce((a, x) => a + n(x.sum_profit), 0) / 1.1))}</td></tr></tfoot>}</table>}
        {tab === 'customers' && <table style={{ fontSize: 13 }}><thead><tr><th>고객명</th><th>사업자번호</th><th>담당자ID</th><th>대표</th><th>연락처</th><th style={{ textAlign: 'right' }}>마일리지</th><th style={{ textAlign: 'right' }}>인센율</th><th>사용</th><th>등록</th></tr></thead><tbody>{R.map((x, i) => <tr key={i}><td><b>{x.custName}</b></td><td style={{ fontFamily: 'monospace', fontSize: 12 }}>{x.bizNo}</td><td>{x.empId}</td><td>{x.ownerName}</td><td>{x.custTel}</td><td style={{ textAlign: 'right' }}>{won(n(x.mileage))}</td><td style={{ textAlign: 'right' }}>{x.incentiveRate}</td><td>{x.useInd}</td><td style={{ fontSize: 12, color: 'var(--muted)' }}>{String(x.regDate ?? '').slice(0, 10)}</td></tr>)}{R.length === 0 && <tr><td colSpan={9} style={{ color: 'var(--muted)', textAlign: 'center', padding: 20 }}>없음</td></tr>}</tbody></table>}
        {tab === 'tax' && <><div style={{ display: 'flex', gap: 10, marginBottom: 10, fontSize: 13 }}><span className="pill" style={{ background: 'var(--bad-soft)', color: 'var(--bad)' }}>미발행 {R.filter(x => x.taxInd !== 'Y').length}건</span><span className="pill" style={{ background: 'var(--ok-soft)', color: 'var(--ok)' }}>발행 {R.filter(x => x.taxInd === 'Y').length}건</span></div>
          <table style={{ fontSize: 13 }}><thead><tr><th>정산번호</th><th>요청일</th><th>승인일</th><th>고객</th><th>상품</th><th style={{ textAlign: 'right' }}>확정 입금액</th><th>발행</th><th>계산서 번호</th></tr></thead><tbody>{[...R].sort((a, b) => (a.taxInd === 'Y' ? 1 : 0) - (b.taxInd === 'Y' ? 1 : 0)).map((x, i) => <tr key={i} style={{ background: x.taxInd !== 'Y' ? 'var(--bad-soft)' : undefined }}><td style={{ fontFamily: 'monospace', fontSize: 12 }}>{x.settlementSeq}</td><td>{String(x.reqDate ?? '').slice(0, 10)}</td><td>{String(x.confirmDate ?? '').slice(0, 10)}</td><td><b>{x.custName}</b></td><td>{x.prodName}</td><td style={{ textAlign: 'right' }}>{won(n(x.confirmAmt))}</td><td>{x.taxInd === 'Y' ? <span className="pill" style={{ background: 'var(--ok-soft)', color: 'var(--ok)' }}>발행</span> : <span className="pill" style={{ background: 'var(--bad-soft)', color: 'var(--bad)' }}>미발행</span>}</td><td style={{ fontSize: 12 }}>{x.invoiceNo}</td></tr>)}{R.length === 0 && <tr><td colSpan={8} style={{ color: 'var(--muted)', textAlign: 'center', padding: 20 }}>없음</td></tr>}</tbody></table></>}
        {tab === 'payroll' && (() => { const by: Record<string, { name: string; cnt: number; rate: number; paid: number; unpaid: number }> = {}; for (const x of R) { const k = String(x.userId ?? ''); by[k] ??= { name: String(x.empName ?? ''), cnt: 0, rate: 0, paid: 0, unpaid: 0 }; by[k].cnt++; const v = n(x.confirmRateAmt); by[k].rate += v; if (x.payYm) by[k].paid += v; else by[k].unpaid += v; } const list = Object.entries(by).sort((a, b) => b[1].rate - a[1].rate);
          return <><div style={{ fontSize: 12.5, color: 'var(--muted)', marginBottom: 10 }}>승인된 정산 건의 담당자 확정수수료 합계 (요청일 {label} 기준). '지급'은 정산 사이트에서 급여년월이 찍힌 건.</div>
            <table style={{ fontSize: 13 }}><thead><tr><th>담당자</th><th style={{ textAlign: 'right' }}>건수</th><th style={{ textAlign: 'right' }}>확정수수료 합</th><th style={{ textAlign: 'right' }}>지급 처리</th><th style={{ textAlign: 'right' }}>미지급</th></tr></thead><tbody>{list.map(([k, v]) => <tr key={k}><td><b>{v.name}</b> <span style={{ fontSize: 11, color: 'var(--muted)' }}>{k}</span></td><td style={{ textAlign: 'right' }}>{v.cnt}</td><td style={{ textAlign: 'right', fontWeight: 600 }}>{won(v.rate)}</td><td style={{ textAlign: 'right', color: 'var(--ok)' }}>{won(v.paid)}</td><td style={{ textAlign: 'right', color: v.unpaid ? '#D97706' : 'var(--muted)' }}>{won(v.unpaid)}</td></tr>)}{list.length === 0 && <tr><td colSpan={5} style={{ color: 'var(--muted)', textAlign: 'center', padding: 20 }}>없음</td></tr>}</tbody>
            {list.length > 0 && <tfoot><tr style={{ fontWeight: 700, background: 'var(--bg)' }}><td>합계</td><td style={{ textAlign: 'right' }}>{list.reduce((a, [, v]) => a + v.cnt, 0)}</td><td style={{ textAlign: 'right' }}>{won(list.reduce((a, [, v]) => a + v.rate, 0))}</td><td style={{ textAlign: 'right' }}>{won(list.reduce((a, [, v]) => a + v.paid, 0))}</td><td style={{ textAlign: 'right' }}>{won(list.reduce((a, [, v]) => a + v.unpaid, 0))}</td></tr></tfoot>}</table></>; })()}
      </div></div>
    </div>
  );
}
