'use client';
const ITEM_MAX = 10;   // 정산 사이트 DB 환불항목 값 길이 (초과 시 사이트가 500)
import { useEffect, useState } from 'react';
import { notify } from '@/components/Toast';
import { loadRefundForm, loadOrigItems, submitRefund, myRefundList, cancelRefund } from './actions';
import { refundCalc } from '@/lib/settlement/refundCalc';
import { addDays } from '@/lib/date/kst';
const w = (v: number) => '₩' + Math.round(v).toLocaleString('ko-KR'); const n = (v: unknown) => Number(String(v ?? '0').replace(/[^\d.-]/g, '')) || 0;
const L = ({ l, v, c }: { l: string; v: React.ReactNode; c?: string }) => <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, padding: '4px 0', borderBottom: '1px solid var(--line)' }}><span style={{ color: 'var(--muted)' }}>{l}</span><b style={{ color: c }}>{v}</b></div>;
export default function RefundClient({ linked, settleId, lastError, today }: { linked: boolean; settleId: string; lastError: string; today: string }) {
  const [from, setFrom] = useState(addDays(today, -60)); const [to, setTo] = useState(today); const [mode, setMode] = useState<'work' | 'req'>('work'); const [fd, setFd] = useState<any>(null); const [err, setErr] = useState(''); const [q, setQ] = useState('');
  const [orig, setOrig] = useState<any>(null); const [origItems, setOrigItems] = useState<{ seq: number; name: string; inputValue: string }[]>([]);
  const [refundDate, setRefundDate] = useState(today); const [cnt, setCnt] = useState(0); const [gubun, setGubun] = useState(''); const [memo, setMemo] = useState(''); const [items, setItems] = useState<{ refundItemId: string; refundItemName: string; inputValue: string }[]>([]);
  const [busy, setBusy] = useState(false); const [rows, setRows] = useState<any[]>([]);
  const load = () => loadRefundForm(from, to).then(x => { if (!x.ok) setErr(x.msg); else { setErr(''); setFd(x); setItems((x.itemDefs ?? []).map(d => ({ ...d, inputValue: '' }))); } });
  const refreshList = () => myRefundList(90).then(x => x.ok ? setRows(x.rows ?? []) : notify(x.msg, 'bad'));
  useEffect(() => { if (linked) { load(); refreshList(); } }, [linked]);
  const refundGubuns = fd?.gubuns ?? [];   // 사이트 환불 화면과 동일: SE02 그룹 B(환불 구분)만
  const dayBefore = (d: string) => { const t = new Date(d + 'T00:00:00Z'); t.setUTCDate(t.getUTCDate() - 1); return t.toISOString().slice(0, 10); };
  const pick = async (p: any) => { setOrig(p); setCnt(n(p.inflowCnt)); setRefundDate(today <= String(p.dateWorkTo) ? (today >= String(p.dateWorkFrom) ? today : String(p.dateWorkFrom)) : String(p.dateWorkTo)); setGubun(['05', '06'].includes(String(p.gubun)) ? (refundGubuns.find((g: any) => g.code === '07')?.code ?? refundGubuns[0]?.code ?? '07') : (refundGubuns.find((g: any) => /환불\s*킵/.test(g.name))?.code ?? refundGubuns.find((g: any) => g.code === '04')?.code ?? refundGubuns[0]?.code ?? '')); setMemo(String(p.memo ?? '')); const x = await loadOrigItems(String(p.settlementSeq), String(p.prodId)); setOrigItems(x.ok ? (x.items ?? []) : []); };
  const c = orig ? refundCalc({ prodAmt: n(orig.prodAmt), saleAmt: n(orig.saleAmt), refundInflowCnt: cnt, dateWorkFrom: String(orig.dateWorkFrom), dateWorkTo: String(orig.dateWorkTo), refundDate, workDay: n(orig.workDay), incentiveRate: n(orig.incentiveRate), prodIncentiveInd: String(orig.prodIncentiveInd ?? 'N'), prodIncentive: n(orig.prodIncentive), gubun }) : null;
  const fixedGubun = orig && ['05', '06'].includes(String(orig.gubun));
  const submit = async () => { if (!orig || !c) return; if (c.err) return notify(c.err, 'bad'); if (!gubun) return notify('환불구분을 선택하세요', 'bad'); { const over = items.find(it => it.inputValue.replace(/,/g, '').trim().length > ITEM_MAX); if (over) return notify(`환불 항목 '${over.refundItemName}' 은 최대 ${ITEM_MAX}자까지 (정산 사이트 DB 제한). 슬롯번호가 여러 개면 메모에 적어주세요.`, 'bad', 7000); } if (!confirm(`환불요청을 접수할까요?\n원 정산 ${orig.settlementSeq} · ${orig.custName} · ${orig.prodName}\n환불일수 ${c.refundWorkDay}일 · 환불금액 ${w(c.refundProdTotalAmt)} · 환불수수료 ${w(c.refundExpectRateAmt)}`)) return; setBusy(true); const x = await submitRefund(orig, { refundDate, refundInflowCnt: cnt, gubun, memo, items }); setBusy(false); notify(x.msg, x.ok ? 'ok' : 'bad'); if (x.ok) { setOrig(null); setOrigItems([]); setItems(items.map(i => ({ ...i, inputValue: '' }))); load(); refreshList(); } };
  if (!linked) return <div className="card" style={{ maxWidth: 560 }}><h3 style={{ margin: '0 0 8px', fontSize: 16 }}>환불요청</h3><div style={{ fontSize: 13 }}>정산 사이트 계정이 연결돼 있지 않습니다. <a href="/me">마이페이지</a>에서 연결하세요.</div></div>;
  const pays = (fd?.payments ?? []).filter((p: any) => (!q || JSON.stringify(p).toLowerCase().includes(q.toLowerCase())) && (mode === 'work' || (String(p.reqDate ?? '').slice(0, 10) >= from && String(p.reqDate ?? '').slice(0, 10) <= to)));
  const st = (s: string) => s === '01' ? { background: '#FDF1DD', color: '#D97706' } : s === '02' ? { background: 'var(--ok-soft)', color: 'var(--ok)' } : { background: 'var(--bg)', color: 'var(--muted)' };
  return (
    <div style={{ display: 'grid', gap: 18 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}><h1 style={{ fontSize: 20, margin: 0 }}>환불요청</h1><span style={{ fontSize: 12.5, color: 'var(--muted)' }}>정산 계정 <b>{settleId}</b> · 승인완료된 내 정산 중 환불</span>{lastError && <span className="pill" style={{ background: 'var(--bad-soft)', color: 'var(--bad)' }}>로그인 실패: 마이페이지에서 다시 연결</span>}</div>
      {err && <div style={{ background: 'var(--bad-soft)', color: 'var(--bad)', padding: '10px 14px', borderRadius: 10, fontSize: 13 }}>{err}</div>}
      <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: 18 }}>
        <div style={{ display: 'grid', gap: 18, alignContent: 'start' }}>
          <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15 }}>1. 환불할 원 정산 선택 <span style={{ fontSize: 12, color: 'var(--muted)', fontWeight: 400 }}>{mode === 'work' ? '검색기간에 작업 중인(작업기간이 겹치는) 승인완료 건 — 정산 사이트와 같은 기준' : '요청일이 검색기간 안인 승인완료 건'}</span></h3>
            <div style={{ display: 'flex', gap: 6, alignItems: 'center', marginBottom: 8, flexWrap: 'wrap' }}><input type="date" value={from} onChange={e => setFrom(e.target.value)} style={{ width: 150 }} /><span>~</span><input type="date" value={to} onChange={e => setTo(e.target.value)} style={{ width: 150 }} /><button className="btn ghost" style={{ padding: '6px 12px', fontSize: 12.5 }} onClick={load}>조회</button><div style={{ display: 'flex', border: '1px solid var(--line)', borderRadius: 8, overflow: 'hidden', fontSize: 12 }}><button type="button" onClick={() => setMode('work')} style={{ padding: '5px 10px', border: 0, background: mode === 'work' ? 'var(--accent-soft)' : 'var(--panel)', color: mode === 'work' ? 'var(--accent)' : 'var(--muted)', cursor: 'pointer' }}>작업기간 기준</button><button type="button" onClick={() => setMode('req')} style={{ padding: '5px 10px', border: 0, background: mode === 'req' ? 'var(--accent-soft)' : 'var(--panel)', color: mode === 'req' ? 'var(--accent)' : 'var(--muted)', cursor: 'pointer' }}>요청일 기준</button></div><input value={q} onChange={e => setQ(e.target.value)} placeholder="고객·상품 검색" style={{ width: 180, padding: '6px 10px' }} /></div>
            <div style={{ maxHeight: 300, overflow: 'auto' }}><table style={{ fontSize: 12.5 }}><thead><tr><th>정산번호</th><th>요청일</th><th>고객</th><th>상품</th><th style={{ textAlign: 'right' }}>유입</th><th>작업기간</th><th style={{ textAlign: 'right' }}>판매총액</th></tr></thead><tbody>
              {pays.map((p: any) => <tr key={p.settlementSeq} onClick={() => pick(p)} style={{ cursor: 'pointer', background: orig?.settlementSeq === p.settlementSeq ? 'var(--accent-soft)' : undefined }}><td style={{ fontFamily: 'monospace', fontSize: 11.5 }}>{p.settlementSeq}</td><td>{String(p.reqDate ?? '').slice(0, 10)}</td><td><b>{p.custName}</b></td><td>{p.prodName}</td><td style={{ textAlign: 'right' }}>{p.inflowCnt}</td><td style={{ whiteSpace: 'nowrap' }}>{String(p.dateWorkFrom).slice(5)}~{String(p.dateWorkTo).slice(5)} ({p.workDay}일)</td><td style={{ textAlign: 'right' }}>{w(n(p.saleTotalAmt))}</td></tr>)}
              {fd && pays.length === 0 && <tr><td colSpan={7} style={{ color: 'var(--muted)', textAlign: 'center', padding: 16 }}>환불 가능한 정산 없음 (이미 환불요청된 건은 제외)</td></tr>}{!fd && !err && <tr><td colSpan={7} style={{ color: 'var(--muted)', padding: 16 }}>불러오는 중…</td></tr>}</tbody></table></div></div>
          <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15, display: 'flex', justifyContent: 'space-between' }}><span>내 환불요청 <span style={{ fontSize: 12, color: 'var(--muted)', fontWeight: 400 }}>최근 90일</span></span><button className="btn ghost" style={{ padding: '3px 10px', fontSize: 12 }} onClick={refreshList}>새로고침</button></h3>
            <div style={{ maxHeight: 280, overflow: 'auto' }}><table style={{ fontSize: 12.5 }}><thead><tr><th>환불번호</th><th>원 정산</th><th>환불요청일</th><th>고객</th><th>상품</th><th style={{ textAlign: 'right' }}>환불일수</th><th style={{ textAlign: 'right' }}>환불금액</th><th style={{ textAlign: 'right' }}>환불수수료</th><th>구분</th><th>상태</th><th></th></tr></thead><tbody>
              {rows.map((r: any) => <tr key={r.refundSettlementSeq}><td style={{ fontFamily: 'monospace', fontSize: 11.5 }}>{r.refundSettlementSeq}</td><td style={{ fontFamily: 'monospace', fontSize: 11.5 }}>{r.settlementSeq}</td><td>{String(r.refundDate ?? '').slice(0, 10)}</td><td>{r.custName}</td><td>{r.prodName}</td><td style={{ textAlign: 'right' }}>{r.dateWorkTo && r.refundDate ? Math.abs(Math.round((new Date(String(r.dateWorkTo).slice(0, 10) + 'T00:00:00Z').getTime() - new Date(String(r.refundDate).slice(0, 10) + 'T00:00:00Z').getTime()) / 864e5)) : r.refundWorkDay}</td><td style={{ textAlign: 'right' }}>{w(n(r.refundProdTotalAmt))}</td><td style={{ textAlign: 'right' }}>{w(n(r.refundExpectRateAmt))}</td><td>{r.gubunName}</td><td><span className="pill" style={st(String(r.applyStatus))}>{r.applyStatusName ?? r.applyStatus}</span></td><td>{String(r.applyStatus) === '01' && <button className="btn ghost" style={{ padding: '2px 8px', fontSize: 11 }} onClick={async () => { if (!confirm(`${r.refundSettlementSeq} 환불요청을 삭제할까요?`)) return; const x = await cancelRefund(String(r.refundSettlementSeq)); notify(x.msg, x.ok ? 'ok' : 'bad'); refreshList(); load(); }}>삭제</button>}</td></tr>)}
              {rows.length === 0 && <tr><td colSpan={11} style={{ color: 'var(--muted)', textAlign: 'center', padding: 16 }}>없음</td></tr>}</tbody></table></div></div>
        </div>
        <div className="card"><h3 style={{ margin: '0 0 10px', fontSize: 15 }}>2. 환불 내용</h3>
          {!orig ? <div style={{ fontSize: 13, color: 'var(--muted)' }}>왼쪽에서 원 정산을 선택하세요.</div> : c && <div style={{ display: 'grid', gap: 10 }}>
            <div style={{ fontSize: 13, background: 'var(--bg)', borderRadius: 10, padding: 10 }}><b>{orig.custName}</b> · {orig.prodName} · <span style={{ fontFamily: 'monospace', fontSize: 12 }}>{orig.settlementSeq}</span><div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 4 }}>작업 {orig.dateWorkFrom} ~ {orig.dateWorkTo} ({orig.workDay}일) · 유입 {orig.inflowCnt} · 상품가 {orig.prodAmt} · 판매가 {orig.saleAmt} · 인센율 {orig.incentiveRate}{String(orig.prodIncentiveInd) === 'Y' ? ' · 상품인센' : ''}</div>
              {origItems.length > 0 && <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 6, fontSize: 12 }}>{origItems.map(it => <span key={it.seq} style={{ background: 'var(--panel)', border: '1px solid var(--line)', borderRadius: 6, padding: '2px 8px' }}>{it.name}: <b>{it.inputValue || '-'}</b></span>)}</div>}</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
              <div><label style={{ fontSize: 12, color: 'var(--muted)' }}>환불요청일 *</label><input type="date" value={refundDate} min={dayBefore(String(orig.dateWorkFrom))} max={String(orig.dateWorkTo)} onChange={e => setRefundDate(e.target.value)} /><div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 2 }}>전체 기간 환불(1일 작업 포함)은 작업시작일 <b>전날</b>({dayBefore(String(orig.dateWorkFrom)).slice(5).replace('-', '/')})로 입력</div></div>
              <div><label style={{ fontSize: 12, color: 'var(--muted)' }}>환불 유입수</label><input type="number" value={cnt} onChange={e => setCnt(e.target.value === '' ? 0 : Number(e.target.value))} /></div>
              <div><label style={{ fontSize: 12, color: 'var(--muted)' }}>환불구분 *</label><select value={gubun} disabled={!!fixedGubun} onChange={e => setGubun(e.target.value)}>{refundGubuns.map((g: any) => <option key={g.code} value={g.code}>{g.name}</option>)}</select><div style={{ fontSize: 11, color: 'var(--muted)' }}>{fixedGubun ? '선입금 원건 → 선입금 환불(07) 고정' : '사이트 환불 화면과 같은 환불 구분 목록'}</div></div>
            </div>
            <input value={memo} onChange={e => setMemo(e.target.value)} placeholder="메모" />
            {items.length > 0 && <div style={{ border: '1px solid var(--line)', borderRadius: 10, padding: 10 }}><div style={{ fontSize: 12.5, fontWeight: 600, marginBottom: 6 }}>환불 항목 <span style={{ fontSize: 11.5, color: 'var(--muted)', fontWeight: 400 }}>정산 사이트에 등록된 항목 · 칸당 최대 {ITEM_MAX}자 (사이트 DB 제한, 쉼표는 저장 시 제거됨)</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px,1fr))', gap: 8 }}>{items.map((it, k) => { const len = it.inputValue.replace(/,/g, '').trim().length; return <div key={it.refundItemId}><label style={{ fontSize: 11.5, color: 'var(--muted)' }}>{it.refundItemName} <span style={{ color: len > ITEM_MAX ? 'var(--bad)' : 'var(--muted)' }}>{len}/{ITEM_MAX}</span></label><input value={it.inputValue} maxLength={ITEM_MAX + 10} style={len > ITEM_MAX ? { borderColor: 'var(--bad)' } : undefined} onChange={e => setItems(a => a.map((x, j) => j === k ? { ...x, inputValue: e.target.value } : x))} /></div>; })}</div></div>}
            <div style={{ background: 'var(--bg)', borderRadius: 10, padding: 10 }}>
              {c.err ? <div style={{ color: 'var(--bad)', fontSize: 13 }}>{c.err}</div> : <><L l="환불일수 (작업종료일 − 환불요청일)" v={`${c.refundWorkDay}일 / ${orig.workDay}일`} /><L l="환불금액 (판매가 × 유입 × 환불일수)" v={w(c.refundProdTotalAmt)} /><L l="상품가 기준 금액" v={w(c.refundSaleTotalAmt)} /><L l="환불수수료 (담당자 차감)" v={w(c.refundExpectRateAmt)} c={c.refundExpectRateAmt < 0 ? 'var(--bad)' : 'var(--accent)'} /></>}
            </div>
            <div style={{ fontSize: 11.5, color: 'var(--muted)' }}>승인되면 사이트가 환불금액을 입금 확정액으로, 환불수수료를 담당자 확정수수료로 기록합니다. 환불구분이 킵(04)이면 환불금액이 고객 킵으로 적립됩니다.</div>
            <div style={{ display: 'flex', gap: 8 }}><button className="btn" disabled={busy || !!c.err || !gubun} onClick={submit}>{busy ? '접수 중…' : '환불요청 접수'}</button><button className="btn ghost" onClick={() => setOrig(null)}>취소</button></div>
          </div>}
        </div>
      </div>
    </div>
  );
}
