'use client';
import { useEffect, useState } from 'react';
import { notify } from '@/components/Toast';
import { loadForm, pickCustomer, pickProduct, submitRequest, myList, cancelMine, suggestSale, selfTest, requestItems } from './actions';
import { calc, type ReqInput } from '@/lib/settlement/calc';
const w = (v: number) => '₩' + Math.round(v).toLocaleString('ko-KR');
const L = ({ l, v, c }: { l: string; v: React.ReactNode; c?: string }) => <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, padding: '4px 0', borderBottom: '1px solid var(--line)' }}><span style={{ color: 'var(--muted)' }}>{l}</span><b style={{ color: c }}>{v}</b></div>;
export default function RequestClient({ linked, settleId, lastError, today, canAddCustomer }: { linked: boolean; settleId: string; lastError: string; today: string; canAddCustomer: boolean }) {
  const [detail, setDetail] = useState<any>(null); const [lq, setLq] = useState(''); const [detailItems, setDetailItems] = useState<{ seq: number; name: string; inputValue: string }[] | null>(null);
  const openDetail = async (r: any) => { setDetail(r); setDetailItems(null); const x = await requestItems(String(r.settlementSeq), String(r.prodId)); setDetailItems(x.ok ? (x.items ?? []) : []); };
  const [fd, setFd] = useState<any>(null); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false); const [rows, setRows] = useState<any[]>([]); const [listErr, setListErr] = useState('');
  const [i, setI] = useState<ReqInput>({ prodId: '', custId: '', prodAmt: 0, prodIncentive: 0, saleAmt: 0, inflowCnt: 0, dateWorkFrom: today, dateWorkTo: today, saleTotalAmt: 0, gubun: '', mileageUseInd: false, useMileage: 0, custRate: 0, empRate: 0, existMileage: 0 });
  const [test, setTest] = useState<any>(null); const [reqDate, setReqDate] = useState(today); const [memo, setMemo] = useState(''); const [items, setItems] = useState<{ prodId: string; seq: number; name: string; inputValue: string }[]>([]); const [custQ, setCustQ] = useState(''); const [prodQ, setProdQ] = useState(''); const [newCust, setNewCust] = useState(false); const [saleHint, setSaleHint] = useState<number | null>(null);
  const reloadForm = () => loadForm().then(x => { if (x.ok) setFd(x.data); });
  const trySuggest = async (custId: string, prodId: string) => { if (!custId || !prodId) return; const x = await suggestSale(custId, prodId); if (x.ok && x.saleAmt) { setSaleHint(x.saleAmt); setI(s => s.saleAmt ? s : { ...s, saleAmt: x.saleAmt! }); } else setSaleHint(null); };
  const refreshList = () => myList(60).then(x => x.ok ? setRows(x.rows ?? []) : setListErr(x.msg));
  useEffect(() => { if (!linked) return; loadForm().then(x => { if (!x.ok) setErr(x.msg); else { setFd(x.data); setI(s => ({ ...s, empRate: x.data!.empRate, gubun: x.data!.gubuns[0]?.code ?? '' })); } }); refreshList(); }, [linked]);
  const c = calc(i); const fixed = ['05', '06'].includes(i.gubun);
  const onCust = async (bizNo: string) => { setI(s => ({ ...s, custId: bizNo })); if (!bizNo) return; const x = await pickCustomer(bizNo); if (x.ok) setI(s => ({ ...s, existMileage: x.mileage!, custRate: x.rate! })); else notify(x.msg, 'bad'); trySuggest(bizNo, i.prodId); };
  const onProd = async (prodId: string) => { setI(s => ({ ...s, prodId })); setItems([]); if (!prodId) return; const x = await pickProduct(prodId); if (x.ok) { setI(s => ({ ...s, prodAmt: x.prodAmt!, prodIncentive: x.prodIncentive! })); setItems((x.items ?? []).map(it => ({ ...it, inputValue: '' }))); } else notify(x.msg, 'bad'); trySuggest(i.custId, prodId); };
  const submit = async () => { if (!confirm(`정산요청을 접수할까요?\n고객: ${fd.customers.find((x: any) => x.bizNo === i.custId)?.name} / 상품: ${fd.products.find((x: any) => x.prodId === i.prodId)?.name}\n판매총액 ${w(i.saleTotalAmt)} · 예상정산 ${w(c.expectRateAmt)}`)) return; setBusy(true); const x = await submitRequest({ ...i, reqDate, memo, items }); setBusy(false); notify(x.msg, x.ok ? 'ok' : 'bad'); if (x.ok) { setI(s => ({ ...s, custId: '', prodId: '', prodAmt: 0, prodIncentive: 0, saleAmt: 0, inflowCnt: 0, saleTotalAmt: 0, mileageUseInd: false, useMileage: 0, custRate: 0, existMileage: 0 })); setItems([]); setMemo(''); refreshList(); } };
  if (!linked) return <div className="card" style={{ maxWidth: 560 }}><h3 style={{ margin: '0 0 8px', fontSize: 16 }}>정산요청</h3><div style={{ fontSize: 13 }}>정산 사이트 계정이 연결돼 있지 않습니다. <a href="/me">마이페이지</a>에서 정산 사이트 아이디·비밀번호를 연결하면 여기서 바로 정산요청을 넣을 수 있습니다.</div></div>;
  const custs = (fd?.customers ?? []).filter((x: any) => !custQ || x.name.toLowerCase().includes(custQ.toLowerCase()));
  const stColor = (s: string) => s === '01' ? { background: '#FDF1DD', color: '#D97706' } : s === '02' ? { background: 'var(--ok-soft)', color: 'var(--ok)' } : { background: 'var(--bg)', color: 'var(--muted)' };
  const D = ({ l, v }: { l: string; v: React.ReactNode }) => <div style={{ background: 'var(--bg)', borderRadius: 8, padding: '6px 10px' }}><div style={{ fontSize: 10.5, color: 'var(--muted)' }}>{l}</div><div style={{ fontSize: 13, fontWeight: 600 }}>{v ?? '-'}</div></div>;
  const detailModal = detail && <div style={{ position: 'fixed', inset: 0, background: 'rgba(16,26,74,.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 }} onClick={() => setDetail(null)}>
    <div className="card" style={{ width: 640, maxHeight: '90vh', overflow: 'auto' }} onClick={e => e.stopPropagation()}>
      <h3 style={{ margin: '0 0 6px', fontSize: 16, display: 'flex', justifyContent: 'space-between' }}><span>요청 상세 <span style={{ fontFamily: 'monospace', fontSize: 13, color: 'var(--muted)' }}>{detail.settlementSeq}</span></span><span className="pill" style={stColor(String(detail.applyStatus))}>{detail.applyStatusName ?? detail.applyStatus}</span></h3>
      <div style={{ fontSize: 13, marginBottom: 10 }}><b>{detail.custName}</b> · {detail.prodName} · {detail.gubunName ?? ''} · 요청일 {String(detail.reqDate ?? '').slice(0, 10)}{detail.memo ? ` · 메모: ${detail.memo}` : ''}</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 6 }}>
        <D l="작업 기간" v={`${String(detail.dateWorkFrom ?? '').slice(5)} ~ ${String(detail.dateWorkTo ?? '').slice(5)}`} /><D l="작업일수" v={`${detail.workDay ?? '-'}일`} /><D l="유입수" v={detail.inflowCnt} /><D l="상품가 / 판매가" v={`${detail.prodAmt ?? '-'} / ${detail.saleAmt ?? '-'}`} />
        <D l="상품총액 (VAT)" v={w(Number(detail.prodTotalAmt) || 0)} /><D l="판매총액 (VAT)" v={w(Number(detail.saleTotalAmt) || 0)} /><D l="입금예정" v={w(Number(detail.expectAmt) || 0)} /><D l="적용 인센율" v={detail.incentiveRate} />
        <D l="킵 사용" v={String(detail.mileageUseInd) === 'Y' ? w(Number(detail.useMileage) || 0) : '없음'} /><D l="예상 정산금액 (수수료)" v={<span style={{ color: 'var(--accent)' }}>{w(Number(detail.expectRateAmt) || 0)}</span>} />
        {String(detail.applyStatus) === '02' && <><D l="확정 입금액" v={w(Number(detail.confirmAmt) || 0)} /><D l="확정 수수료" v={w(Number(detail.confirmRateAmt) || 0)} /></>}
      </div>
      {detail.confirmDate && <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 8 }}>승인일 {String(detail.confirmDate).slice(0, 10)} · 승인번호 {detail.confirmSeq}</div>}
      <div style={{ marginTop: 10 }}><div style={{ fontSize: 12.5, fontWeight: 600, marginBottom: 4 }}>상품 정보</div>{detailItems === null ? <div style={{ fontSize: 12, color: 'var(--muted)' }}>불러오는 중…</div> : detailItems.length === 0 ? <div style={{ fontSize: 12, color: 'var(--muted)' }}>등록된 항목 없음</div> : <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>{detailItems.map(it => <span key={it.seq} style={{ background: 'var(--bg)', border: '1px solid var(--line)', borderRadius: 6, padding: '3px 8px', fontSize: 12.5 }}>{it.name}: <b>{it.inputValue || '-'}</b></span>)}</div>}</div>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 12 }}><button className="btn ghost" onClick={() => setDetail(null)}>닫기</button></div>
    </div></div>;
  return (
    <div style={{ display: 'grid', gap: 18 }}>
      {detailModal}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><h1 style={{ fontSize: 20, margin: 0 }}>정산요청</h1><span style={{ fontSize: 12.5, color: 'var(--muted)' }}>정산 계정 <b>{settleId}</b>로 접수 · 정산 사이트와 동일 계산</span>{lastError && <span className="pill" style={{ background: 'var(--bad-soft)', color: 'var(--bad)' }}>로그인 실패: 마이페이지에서 다시 연결</span>}<button className="btn ghost" style={{ padding: '4px 10px', fontSize: 12 }} onClick={async () => { setTest({ running: true }); const x = await selfTest(); setTest(x); }}>{test?.running ? '점검 중…' : '연결 점검'}</button></div>
      {test && !test.running && <div className="card" style={{ borderColor: test.ok ? 'var(--ok)' : 'var(--bad)' }}><b style={{ fontSize: 13 }}>{test.msg}</b>{(test.steps ?? []).map((st: any, k: number) => <div key={k} style={{ fontSize: 12.5, padding: '3px 0' }}><span style={{ color: st.ok ? 'var(--ok)' : 'var(--bad)', fontWeight: 700 }}>{st.ok ? 'OK' : 'FAIL'}</span> {st.name} <span style={{ color: 'var(--muted)' }}>— {st.note}</span></div>)}</div>}
      {err && <div style={{ background: 'var(--bad-soft)', color: 'var(--bad)', padding: '10px 14px', borderRadius: 10, fontSize: 13 }}>{err}</div>}
      <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: 18 }}>
        <div className="card"><h3 style={{ margin: '0 0 12px', fontSize: 15 }}>새 요청</h3>
          {!fd ? <div style={{ fontSize: 13, color: 'var(--muted)' }}>정산 사이트에서 고객·상품 목록 불러오는 중…</div> : <div style={{ display: 'grid', gap: 10 }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 8 }}><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>정산요청일</label><input type="date" value={reqDate} onChange={e => setReqDate(e.target.value)} /></div><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>메모</label><input value={memo} onChange={e => setMemo(e.target.value)} placeholder="메모 (선택)" /></div></div>
            <div><label style={{ fontSize: 12, color: 'var(--muted)', display: 'flex', alignItems: 'center', gap: 8 }}>고객 <input value={custQ} onChange={e => setCustQ(e.target.value)} placeholder="검색" style={{ width: 140, padding: '2px 8px', fontSize: 12 }} />{canAddCustomer && <button type="button" className="btn ghost" style={{ padding: '2px 8px', fontSize: 11 }} onClick={() => setNewCust(!newCust)}>{newCust ? '등록 닫기' : '+ 새 고객'}</button>}</label>{custQ && <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, margin: '6px 0' }}>{custs.slice(0, 8).map((x: any) => <button type="button" key={x.bizNo} className="btn ghost" style={{ padding: '4px 10px', fontSize: 12.5, background: i.custId === x.bizNo ? 'var(--accent-soft)' : undefined, borderColor: i.custId === x.bizNo ? 'var(--accent)' : undefined }} onClick={() => onCust(x.bizNo)}>{x.name}{x.empId ? <span style={{ color: 'var(--muted)', fontSize: 11 }}> {x.empId}</span> : null}</button>)}{custs.length === 0 && <span style={{ fontSize: 12, color: 'var(--muted)' }}>일치하는 고객 없음{canAddCustomer ? " — '+ 새 고객'으로 등록" : ' — 관리팀에 고객 등록 요청'}</span>}{custs.length > 8 && <span style={{ fontSize: 12, color: 'var(--muted)' }}>외 {custs.length - 8}개 (더 입력)</span>}</div>}
              <select value={i.custId} onChange={e => onCust(e.target.value)}><option value="">고객 선택 ({custs.length})</option>{(custQ ? [...custs, ...(fd.customers.filter((x: any) => x.bizNo === i.custId && !custs.includes(x)))] : custs).map((x: any) => <option key={x.bizNo} value={x.bizNo}>{x.name}{x.empId ? ` · ${x.empId}` : ''}</option>)}</select>{i.custId && <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 3 }}>잔여 킵 {w(i.existMileage)} · 고객 인센율 {i.custRate || '없음(직원율 ' + i.empRate + ')'}</div>}
              {newCust && <div style={{ marginTop: 8, padding: 10, border: '1px dashed var(--accent)', borderRadius: 10, fontSize: 12.5 }}>새 고객은 <a href="/settle-customers" target="_blank" rel="noreferrer"><b>고객 등록 · 배정</b></a> 화면에서 담당 직원 배정까지 한 번에 등록하세요. 등록 후 이 화면에서 <button type="button" className="btn ghost" style={{ padding: '2px 8px', fontSize: 11.5 }} onClick={async () => { await reloadForm(); notify('고객 목록 새로고침', 'ok'); }}>고객 목록 새로고침</button> 을 누르면 바로 선택할 수 있습니다 (본인에게 배정된 고객만 보임).</div>}</div>
            <div><label style={{ fontSize: 12, color: 'var(--muted)', display: 'flex', alignItems: 'center', gap: 8 }}>상품 <input value={prodQ} onChange={e => { const q = e.target.value; setProdQ(q); const m = fd.products.filter((x: any) => q && x.name.toLowerCase().includes(q.toLowerCase())); if (m.length === 1 && m[0].prodId !== i.prodId) onProd(m[0].prodId); }} placeholder="검색 (예: 셀팜)" style={{ width: 160, padding: '2px 8px', fontSize: 12 }} /></label>
              {prodQ && (() => { const m = fd.products.filter((x: any) => x.name.toLowerCase().includes(prodQ.toLowerCase())).slice(0, 8); return <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, margin: '6px 0' }}>{m.map((x: any) => <button type="button" key={x.prodId} className="btn ghost" style={{ padding: '4px 10px', fontSize: 12.5, background: i.prodId === x.prodId ? 'var(--accent-soft)' : undefined, borderColor: i.prodId === x.prodId ? 'var(--accent)' : undefined }} onClick={() => { onProd(x.prodId); }}>{x.name}</button>)}{m.length === 0 && <span style={{ fontSize: 12, color: 'var(--muted)' }}>일치하는 상품 없음</span>}</div>; })()}
              <select value={i.prodId} onChange={e => onProd(e.target.value)}><option value="">상품 선택</option>{fd.products.filter((x: any) => !prodQ || x.name.toLowerCase().includes(prodQ.toLowerCase()) || x.prodId === i.prodId).map((x: any) => <option key={x.prodId} value={x.prodId}>{x.name}</option>)}</select>{i.prodId && <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 3 }}>상품가 {i.prodAmt}{i.prodIncentive > 0 ? ` · 상품 인센 ${i.prodIncentive}` : ''}</div>}</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>요청구분</label><select value={i.gubun} onChange={e => setI(s => ({ ...s, gubun: e.target.value, mileageUseInd: ['05', '06'].includes(e.target.value) ? false : s.mileageUseInd }))}>{fd.gubuns.map((g: any) => <option key={g.code} value={g.code}>{g.name}</option>)}</select></div><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>판매가 {saleHint ? <span style={{ color: 'var(--accent)' }}>· 지난 요청 {saleHint}</span> : ''}</label><input type="number" step="0.1" value={i.saleAmt} onChange={e => setI(s => ({ ...s, saleAmt: e.target.value === '' ? 0 : Number(e.target.value) }))} placeholder="고객별 단가 (0 가능)" /></div><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>유입수</label><input type="number" value={i.inflowCnt} onChange={e => setI(s => ({ ...s, inflowCnt: e.target.value === '' ? 0 : Number(e.target.value) }))} placeholder="0 가능 (킵 등)" /></div></div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>작업 시작</label><input type="date" value={i.dateWorkFrom} onChange={e => setI(s => ({ ...s, dateWorkFrom: e.target.value }))} /></div><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>작업 종료</label><input type="date" value={i.dateWorkTo} onChange={e => setI(s => ({ ...s, dateWorkTo: e.target.value }))} /></div><div><label style={{ fontSize: 12, color: 'var(--muted)' }}>작업일수</label><div style={{ padding: '9px 0', fontWeight: 700 }}>{c.workDay}일</div></div></div>
            <div><label style={{ fontSize: 12, color: 'var(--bad)', fontWeight: 600 }}>판매총액 (VAT 포함, 직접 입력) *</label><input type="number" value={i.saleTotalAmt} onChange={e => setI(s => ({ ...s, saleTotalAmt: e.target.value === '' ? 0 : Number(e.target.value) }))} placeholder={i.saleAmt && i.inflowCnt ? `참고: 판매가×유입수×작업일 = ${(i.saleAmt * i.inflowCnt * c.workDay).toLocaleString()}` : ''} /></div>
            {items.length > 0 && <div style={{ border: '1px solid var(--line)', borderRadius: 10, padding: 10 }}><div style={{ fontSize: 12.5, fontWeight: 600, marginBottom: 6 }}>상품 정보 <span style={{ fontSize: 11.5, color: 'var(--muted)', fontWeight: 400 }}>정산 사이트에서 이 상품에 요구하는 항목</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 8 }}>{items.map((it, k) => <div key={it.seq}><label style={{ fontSize: 11.5, color: 'var(--muted)' }}>{it.name}</label><input value={it.inputValue} onChange={e => setItems(arr => arr.map((x, j) => j === k ? { ...x, inputValue: e.target.value } : x))} /></div>)}</div></div>}
            <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}><label style={{ fontSize: 13, display: 'flex', alignItems: 'center', gap: 6 }}><input type="checkbox" checked={i.mileageUseInd} disabled={fixed || i.existMileage <= 0} onChange={e => setI(s => ({ ...s, mileageUseInd: e.target.checked, useMileage: e.target.checked ? s.useMileage : 0 }))} style={{ width: 16, height: 16 }} />킵 사용</label>{i.mileageUseInd && <input type="number" value={i.useMileage || ''} onChange={e => setI(s => ({ ...s, useMileage: Math.min(Number(e.target.value) || 0, s.existMileage) }))} placeholder={`최대 ${i.existMileage.toLocaleString()}`} style={{ width: 160 }} />}</div>
            <div style={{ background: 'var(--bg)', borderRadius: 10, padding: 10 }}><L l="상품총액 (상품가×유입수×작업일)" v={w(c.prodTotalAmt)} /><L l={`적용 인센율`} v={c.prodIncentiveInd === 'Y' ? '상품 인센' : String(c.incentiveRate)} /><L l="영업이익 (판매총액−상품총액)" v={w(c.costAmt)} c={c.costAmt < 0 ? 'var(--bad)' : undefined} /><L l="입금예정 (판매총액−킵)" v={w(c.expectAmt)} /><L l="예상 정산금액 (수수료)" v={w(c.expectRateAmt)} c="var(--accent)" /></div>
            <div><button className="btn" disabled={busy || !i.custId || !i.prodId || !i.gubun} onClick={submit}>{busy ? '접수 중…' : '정산요청 접수'}</button></div>
          </div>}</div>
        <div className="card"><h3 style={{ margin: '0 0 12px', fontSize: 15, display: 'flex', justifyContent: 'space-between' }}><span>내 요청 <span style={{ fontSize: 12, color: 'var(--muted)', fontWeight: 400 }}>최근 60일 · 행 클릭 = 상세</span></span><span style={{ display: 'flex', gap: 6 }}><input value={lq} onChange={e => setLq(e.target.value)} placeholder="고객·상품·정산번호·상태 검색" style={{ width: 220, minHeight: 36, padding: '0 10px', fontSize: 13 }} /><button className="btn ghost" style={{ padding: '3px 10px', fontSize: 12 }} onClick={refreshList}>새로고침</button></span></h3>
          {(() => { const q = lq.trim().toLowerCase(); const shown = q ? rows.filter((r: any) => [r.custName, r.prodName, r.settlementSeq, r.applyStatusName, r.gubunName].some(v => String(v ?? '').toLowerCase().includes(q))) : rows; const sale = shown.reduce((a: number, r: any) => a + (Number(r.saleTotalAmt) || 0), 0); const rate = shown.reduce((a: number, r: any) => a + (Number(r.expectRateAmt) || 0), 0); const ok = shown.filter((r: any) => String(r.applyStatus) === '02'); const okSale = ok.reduce((a: number, r: any) => a + (Number(r.saleTotalAmt) || 0), 0);
            return <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', fontSize: 13, marginBottom: 8, color: 'var(--muted)' }}><span>{q ? `검색 ${shown.length}건` : `전체 ${shown.length}건`}</span><span>판매총액 합 <b style={{ color: 'var(--ink)' }}>{w(sale)}</b></span><span>승인완료 {ok.length}건 판매총액 <b style={{ color: 'var(--ink)' }}>{w(okSale)}</b></span><span>예상 정산 합 <b style={{ color: 'var(--accent)' }}>{w(rate)}</b></span></div>; })()}
          {listErr && <div style={{ color: 'var(--bad)', fontSize: 13 }}>{listErr}</div>}
          <div style={{ maxHeight: 600, overflow: 'auto' }}><table style={{ fontSize: 12.5 }}><thead><tr><th>정산번호</th><th>요청일</th><th>고객</th><th>상품</th><th style={{ textAlign: 'right' }}>판매총액</th><th style={{ textAlign: 'right' }}>예상정산</th><th>상태</th><th></th></tr></thead><tbody>
            {rows.filter((r: any) => { const q = lq.trim().toLowerCase(); return !q || [r.custName, r.prodName, r.settlementSeq, r.applyStatusName, r.gubunName].some(v => String(v ?? '').toLowerCase().includes(q)); }).map((r: any) => <tr key={r.settlementSeq} onClick={() => openDetail(r)} style={{ cursor: 'pointer' }}><td style={{ fontFamily: 'monospace', fontSize: 11.5, whiteSpace: 'nowrap' }}>{r.settlementSeq}</td><td style={{ whiteSpace: 'nowrap' }}>{String(r.reqDate ?? '').slice(0, 10)}</td><td>{r.custName}</td><td>{r.prodName}</td><td style={{ textAlign: 'right' }}>{w(Number(r.saleTotalAmt) || 0)}</td><td style={{ textAlign: 'right' }}>{w(Number(r.expectRateAmt) || 0)}</td><td><span className="pill" style={{ ...stColor(String(r.applyStatus)), whiteSpace: 'nowrap' }}>{r.applyStatusName ?? r.applyStatus}</span></td><td onClick={e => e.stopPropagation()}>{String(r.applyStatus) === '01' && <button className="btn ghost" style={{ padding: '2px 8px', fontSize: 11, whiteSpace: 'nowrap' }} onClick={async () => { if (!confirm(`${r.settlementSeq} 요청취소할까요?`)) return; const x = await cancelMine(String(r.settlementSeq)); notify(x.msg, x.ok ? 'ok' : 'bad'); refreshList(); }}>요청취소</button>}</td></tr>)}
            {rows.length === 0 && <tr><td colSpan={8} style={{ color: 'var(--muted)', textAlign: 'center', padding: 20 }}>없음</td></tr>}</tbody></table></div></div>
      </div>
    </div>
  );
}
